# runtime: go
# api_version: go1

# handlers:
# - url: /.*
#   script: _go_app

# threadsafe: true

# automatic_scaling:
#   min_idle_instances: automatic
#   max_idle_instances: 1
#   min_pending_latency: 3000ms
#   max_pending_latency: automatic

runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

threadsafe: true